- hosts: "{{hosts}}"
  gather_facts: false
  remote_user: "{{user}}"
  vars:
    - deploy_file:  /home/ci/.jenkins/workspace/fco-docekr-spring-demo/target/demo-0.0.1-SNAPSHOT.jar
    - service_name:  demo
    - deploy_path: "~/app/{{service_name}}"
    - service_port: 8000
    - start_cmd:  "nohup java  -jar  11272050_demo-0.0.1-SNAPSHOT.jar >> demo.log&"
  roles:
    - spring 
